### ISSUE TITLE
go build ent/runtime  panic

### ISSUE THREAD

**Issue by paineZhang** [ent/ent#1926]
There is a panic on ent/runtime,when run `go build`.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
It  gets a panic when run `go build` , but not run `go run main.go`.The output is:
```
# wing/models/ent/runtime
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x3fe179]

goroutine 1 [running]:
cmd/compile/internal/ir.MethodExprName(...)
        c:/go/src/cmd/compile/internal/ir/expr.go:1067
cmd/compile/internal/ir.(*bottomUpVisitor).visit.func2({0xc99e88, 0xc00080c6c0})
        c:/go/src/cmd/compile/internal/ir/scc.go:94 +0xd9
cmd/compile/internal/ir.Visit.func1({0xc99e88, 0xc00080c6c0})
        c:/go/src/cmd/compile/internal/ir/visit.go:105 +0x30
cmd/compile/internal/ir.(*ConvExpr).doChildren(0xc000805c20, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:437 +0x62
cmd/compile/internal/ir.DoChildren(...)
        c:/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xc98970, 0xc000805c20})
        c:/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.doNodes({0xc0007b3dc0, 0x4, 0xc99848}, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:1440 +0x67
cmd/compile/internal/ir.(*CallExpr).doChildren(0xc000359b90, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:263 +0x85
cmd/compile/internal/ir.DoChildren(...)
        c:/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xc983f8, 0xc000359b90})
        c:/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.doNodes({0xc0007e0900, 0x1, 0x3f542e}, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:1440 +0x67
cmd/compile/internal/ir.(*AssignListStmt).doChildren(0xc00080c780, 0xc00080c780)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:100 +0x7f
cmd/compile/internal/ir.DoChildren(...)
        c:/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xc97e80, 0xc00080c780})
        c:/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.doNodes({0xc00080b0c0, 0x2, 0x3fe0d4}, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:1440 +0x67
cmd/compile/internal/ir.(*BlockStmt).doChildren(0xc0007b3e00, 0xc0007b3e00)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:222 +0x57
cmd/compile/internal/ir.DoChildren(...)
        c:/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xc98268, 0xc0007b3e00})
        c:/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.doNodes({0xc0007b3e40, 0x4, 0xc00089c228}, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:1440 +0x67
cmd/compile/internal/ir.(*ConvExpr).doChildren(0xc000805d60, 0xc00089aaf8)
        c:/go/src/cmd/compile/internal/ir/node_gen.go:434 +0x3c
cmd/compile/internal/ir.DoChildren(...)
        c:/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xc98970, 0xc000805d60})
cmd/compile/internal/ir.DoChildren(...)
        c:/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xc98bc8, 0xc0000fe160})
        c:/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.Visit({0xc98bc8, 0xc0000fe160}, 0xc0008946b0)
        c:/go/src/cmd/compile/internal/ir/visit.go:108 +0xb8
cmd/compile/internal/ir.(*bottomUpVisitor).visit(0xc000898a80, 0xc0000fe160)
        c:/go/src/cmd/compile/internal/ir/scc.go:87 +0x1b3
cmd/compile/internal/ir.VisitFuncsBottomUp({0xc0000dee00, 0x12, 0x2}, 0xb5d428)
        c:/go/src/cmd/compile/internal/ir/scc.go:60 +0x105
cmd/compile/internal/escape.Funcs(...)
        c:/go/src/cmd/compile/internal/escape/escape.go:1821
cmd/compile/internal/gc.Main(0xb5d328)
        c:/go/src/cmd/compile/internal/gc/main.go:253 +0xcef
main.main()
        c:/go/src/cmd/compile/main.go:55 +0xdd
```

## Expected Behavior 🤔

go build pass.

## Steps to Reproduce 🕹

Steps:

1. Use entc as module.Set `gen.AllFeatures` to `Features` of `gen.Config`.
2. Create a model such as `User`.
3. Add `func Policy()` for User type.
4. Add `_ "ent/runtime"` close to where the database driver is imported.
5. Run `go run -mod=mod ./entc.go`  to generate code.
6. Run `go build`.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | 0.9.1   |
| Database    | Mysql8   |
| Driver      | github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this @paineZhang 😃 

I wasn't able to reproduce this issue and I don't see anything related to ent in the stack trace that can point me to the problem. Can you please create an example repository that reproduces this bug and post it here? Thanks 🙏

**Comment by paineZhang** [comment]
@a8m . I commited the whole codes at here : <https://github.com/paineZhang/entissue>
By the way, my os is windows 10. Hope that helps. And I'll try to reproduce this problem on Linux.

**Comment by paineZhang** [comment]
I use windows docker. It's backend is WSL2.And image is golang 1.17.0. The same thing happened.

**Comment by crossworth** [comment]
Hello, the problem exists on macOS 11.4/go 1.17 as well, `go build` and `go run` panics.
Looks like is this issue: https://github.com/golang/go/issues/48088

With go tip your program do compile.
![image](https://user-images.githubusercontent.com/1251151/132617070-edca80e5-a829-41eb-9526-6ca4f39eab03.png)

**Comment by paineZhang** [comment]
@crossworth . Thanks. Looks like have to wait for golang's new release.
