### ISSUE TITLE
CTE Recursive Query `LIMIT` & `ORDER` conflicted with initial and recursive queries

### ISSUE THREAD

**Issue by vzool** [ent/ent#2167]
I have this error:

```shell
2021/11/25 06:44:50 driver.Query: query=WITH RECURSIVE `undeleted`(`id`, `parent_id`) AS (SELECT `files`.`id`, `files`.`parent_id` FROM `files` WHERE `files`.`parent_id` IS NULL AND `files`.`deleted` = ? UNION ALL SELECT `files`.`id`, `files`.`parent_id` FROM `files` JOIN `undeleted` ON `files`.`parent_id` = `undeleted`.`id` WHERE `files`.`deleted` = ? ORDER BY `deleted` ASC LIMIT 2 ORDER BY `id` ASC LIMIT 1) SELECT `files`.`name` FROM `files` JOIN `undeleted` ON `files`.`id` = `undeleted`.`id` args=[false false]
--- FAIL: TestExample_RecursiveTraversal (0.00s)
panic: near "ORDER": syntax error [recovered]
	panic: near "ORDER": syntax error

goroutine 19 [running]:
testing.tRunner.func1.2({0x70caa0, 0xc00020c0f0})
	/home/vzool/.local/app/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/vzool/.local/app/go/src/testing/testing.go:1212 +0x218
panic({0x70caa0, 0xc00020c0f0})
	/home/vzool/.local/app/go/src/runtime/panic.go:1038 +0x215
entgo.io/ent/examples/fs/ent.(*FileSelect).StringsX(...)
	/home/vzool/Workspace/ent/examples/fs/ent/file_query.go:868
entgo.io/ent/examples/fs.TestExample_RecursiveTraversal(0x0)
	/home/vzool/Workspace/ent/examples/fs/example_test.go:95 +0xc52
testing.tRunner(0xc000107520, 0x737760)
	/home/vzool/.local/app/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/home/vzool/.local/app/go/src/testing/testing.go:1306 +0x35a
FAIL	entgo.io/ent/examples/fs	0.008s
FAIL
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I want to set a `LIMIT` and `ORDER BY` in CTE, I can't do that. and there is no order for them which is which for initial or recursive query. So, if I set `LIMIT` & `ORDER` for initial & recursive queries all `LIMIT` & `ORDERS` for different query will come one after another, like different `SELECT` query, Here is the test case for that:

```golang
// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package main

import (
	"context"
	"fmt"
	"log"
	"testing"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/examples/fs/ent"
	"entgo.io/ent/examples/fs/ent/file"

	_ "github.com/mattn/go-sqlite3"
)

func TestExample_RecursiveTraversal(t *testing.T) { /*[UPDATED-LINE]*/
	client, err := ent.Open("sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	if err != nil {
		log.Fatalf("failed opening connection to sqlite: %v", err)
	}
	defer client.Close()
	ctx := context.Background()
	// Run the auto migration tool.
	if err := client.Schema.Create(ctx); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}

	// Add multiple files in the following tree structure:
	//
	//	a/
	//	├─ b/
	//	│  ├─ ba
	//	│  ├─ bb
	//	│  └─ bc (deleted)
	//	├─ c/ (deleted)
	//	│  ├─ ca
	//	│  └─ cb
	//	└─ d (deleted)
	//
	a := client.File.Create().SetName("a").SaveX(ctx)
	b := client.File.Create().SetName("b").SetParent(a).SaveX(ctx)
	client.File.Create().SetName("ba").SetParent(b).SaveX(ctx)
	client.File.Create().SetName("bb").SetParent(b).SaveX(ctx)
	client.File.Create().SetName("bc").SetParent(b).SetDeleted(true).SaveX(ctx)
	c := client.File.Create().SetName("c").SetParent(a).SetDeleted(true).SaveX(ctx)
	client.File.Create().SetName("ca").SetParent(c).SaveX(ctx)
	client.File.Create().SetName("cb").SetParent(c).SaveX(ctx)
	client.File.Create().SetName("d").SetParent(a).SetDeleted(true).SaveX(ctx)

	// Query undeleted files:
	//
	//	a/
	//	└─ b/
	//	   ├─ ba
	//	   └─ bb
	//
	names := client.Debug().File.Query(). /*[UPDATED-LINE]*/
		Where(func(s *sql.Selector) {
			t1, t2 := sql.Table(file.Table), sql.Table(file.Table)
			with := sql.WithRecursive("undeleted", file.FieldID, file.FieldParentID)
			with.As(
				// The initial `SELECT` statement executed once at the start,
				// and produces the initial row or rows for the recursion.
				sql.Select(t1.Columns(file.FieldID, file.FieldParentID)...).
					From(t1).
					Where(
						sql.And(
							sql.IsNull(t1.C(file.FieldParentID)),
							sql.EQ(t1.C(file.FieldDeleted), false),
						),
					).
					OrderBy(sql.Asc(file.FieldID)).Limit(1). /*[UPDATED-LINE]*/
					// Merge the `SELECT` statement above with the following:
					UnionAll(
						// A `SELECT` statement that produces additional rows and recurses by referring
						// to the CTE name (e.g. "undeleted"), and ends when there are no more new rows.
						sql.Select(t2.Columns(file.FieldID, file.FieldParentID)...).
							From(t2).
							Join(with).
							On(t2.C(file.FieldParentID), with.C(file.FieldID)).
							Where(
								sql.EQ(t1.C(file.FieldDeleted), false),
							).
							OrderBy(sql.Asc(file.FieldDeleted)).Limit(2), /*[UPDATED-LINE]*/
					),
			)
			// Join the root `SELECT` query with the CTE result (`WITH` clause).
			s.Prefix(with).Join(with).On(s.C(file.FieldID), with.C(file.FieldID))
		}).
		Select(file.FieldName).
		StringsX(ctx)
	fmt.Printf("%q\n", names)

	// Output:
	// ["a" "b" "ba" "bb"]
	t.FailNow() /*[UPDATED-LINE]*/
}

```

Above code will generate this `SQL`:

```sql
WITH RECURSIVE `undeleted`(`id`, `parent_id`) AS (
    SELECT
        `files`.`id`,
        `files`.`parent_id`
    FROM
        `files`
    WHERE
        `files`.`parent_id` IS NULL
        AND `files`.`deleted` = ?
    UNION
    ALL
    SELECT
        `files`.`id`,
        `files`.`parent_id`
    FROM
        `files`
        JOIN `undeleted` ON `files`.`parent_id` = `undeleted`.`id`
    WHERE
        `files`.`deleted` = ?
    ORDER BY
        `deleted` ASC
    LIMIT
        2
    ORDER BY
        `id` ASC
    LIMIT
        1
)
SELECT
    `files`.`name`
FROM
    `files`
    JOIN `undeleted` ON `files`.`id` = `undeleted`.`id` args = [false false]
```

## Expected Behavior 🤔

I think the generated `SQL` should be like the following:

```sql
WITH RECURSIVE `undeleted`(`id`, `parent_id`) AS (
    (
        SELECT
            `files`.`id`,
            `files`.`parent_id`
        FROM
            `files`
        WHERE
            `files`.`parent_id` IS NULL
            AND `files`.`deleted` = ?
        ORDER BY
            `id` ASC
        LIMIT
            1
    )
    UNION
    ALL
    (
        SELECT
            `files`.`id`,
            `files`.`parent_id`
        FROM
            `files`
            JOIN `undeleted` ON `files`.`parent_id` = `undeleted`.`id`
        WHERE
            `files`.`deleted` = ?
        ORDER BY
            `deleted` ASC
        LIMIT
            2
    )
)
SELECT
    `files`.`name`
FROM
    `files`
    JOIN `undeleted` ON `files`.`id` = `undeleted`.`id` args = [false false]
```
**Note**: Extra parentheses is required for database engine like PostgreSQL and maybe MySQL too. But, PostgreSQL doesn't support Limit on Recursive queries while it support only on initial one.

## Steps to Reproduce 🕹

Steps:

1. Fork this [repo](https://github.com/ent/ent).
2. Update this file  [ent/examples/fs/example_test.go](https://github.com/ent/ent/blob/master/examples/fs/example_test.go) like example above.
3. Run the unit test.
4. I hope that you face the same beast. ^_^

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | 0.9.1   |
| Database    | SQLite   |
| Driver      | github.com/mattn/go-sqlite3        |

**Comment by a8m** [comment]
Hey @vzool and thanks for raising up this issue. This option is not documented well in entgo.io and I think it should be improved there.

Regarding your expected query - I'm pretty sure it's invalid, as `ORDER BY` and `LIMIT` clauses can't come before a compound-operator (e.g. `UNION ALL`). I tried executing it manually and it returned a syntax error. Please, see the expected grammar in the SQLite website and let me know what do you think.

https://www.sqlite.org/syntax/select-stmt.html
https://www.sqlite.org/lang_with.html.

**Comment by a8m** [comment]
Found now:

> The `initial-select` may be a compound select, but it may not include an ORDER BY, LIMIT, or OFFSET

> The `recursive-select` is allowed to include an ORDER BY, LIMIT, and/or OFFSET but may not use aggregate functions or window functions.

**Comment by a8m** [comment]
Removing the `ORDER BY`/`LIMIT` from the `initial-select` should solve your problem:

```go
// ....
Where(func(s *sql.Selector) {
	t1, t2 := sql.Table(file.Table), sql.Table(file.Table)
	with := sql.WithRecursive("undeleted", file.FieldID, file.FieldParentID)
	with.As(
		// ....
		UnionAll(
			// ...
			sql.Select(t2.Columns(file.FieldID, file.FieldParentID)...).
				// ....
				OrderBy(sql.Asc(file.FieldID)).Limit(2),
		),
	)
})
// ...
```

Closing, as it works as expected. Please, feel free to reopen or continue the discussion if you still need help or you have any problems. Thanks 🙏

**Comment by vzool** [comment]
Hmm, so we reached the limit of `SQLite` capabilities, it looks like the problem is with `PostgreSQL` now, because I thought it will be the same as `SQLite`. I found this bug while I'm testing with `PostgreSQL` and the same example won't work there. As I know `PostgreSQL`on initial-query it supports `LIMIT` & `ORDER`, but for recursive-query, it only supports `ORDER` without `LIMIT`. And the parentheses are required by the `PostgreSQL` database engine. Correct me if I'm wrong.

I think if an update is made to reach the point of the following query, both databases will be covered:
```sql
WITH RECURSIVE `undeleted`(`id`, `parent_id`) AS (
    (
        SELECT
            `files`.`id`,
            `files`.`parent_id`
        FROM
            `files`
        WHERE
            `files`.`parent_id` IS NULL
            AND `files`.`deleted` = ?
        ORDER BY
            `id` ASC
        LIMIT
            1
    )
    UNION
    ALL
    (
        SELECT
            `files`.`id`,
            `files`.`parent_id`
        FROM
            `files`
            JOIN `undeleted` ON `files`.`parent_id` = `undeleted`.`id`
        WHERE
            `files`.`deleted` = ?
        ORDER BY
            `deleted` ASC
        LIMIT
            2
    )
)
SELECT
    `files`.`name`
FROM
    `files`
    JOIN `undeleted` ON `files`.`id` = `undeleted`.`id` args = [false false]
```
What do you think?

**Comment by vzool** [comment]
> Closing, as it works as expected. Please, feel free to reopen or continue the discussion if you still need help or you have any problems. Thanks 🙏

I don't know how to re-open this issue from my side, may you re-open it from your side? Thanks ^_^

**Comment by vzool** [comment]
Here is the same error with `PostgreSQL`:

```shell
Running tool: /home/vzool/.local/app/go/bin/go test -timeout 30s -run ^TestExample_RecursiveTraversal$ entgo.io/ent/examples/fs

2021/11/26 05:38:23 driver.Query: query=WITH RECURSIVE "undeleted"("id", "parent_id") AS (SELECT "files"."id", "files"."parent_id" FROM "files" WHERE "files"."parent_id" IS NULL AND "files"."deleted" = $1 UNION ALL SELECT "files"."id", "files"."parent_id" FROM "files" JOIN "undeleted" ON "files"."parent_id" = "undeleted"."id" WHERE "files"."deleted" = $2 ORDER BY "deleted" ASC LIMIT 2 ORDER BY "id" ASC LIMIT 1) SELECT "files"."name" FROM "files" JOIN "undeleted" ON "files"."id" = "undeleted"."id" args=[false false]
--- FAIL: TestExample_RecursiveTraversal (0.04s)
panic: ERROR: syntax error at or near "ORDER" (SQLSTATE 42601) [recovered]
	panic: ERROR: syntax error at or near "ORDER" (SQLSTATE 42601)

goroutine 6 [running]:
testing.tRunner.func1.2({0x797980, 0xc00022c0f0})
	/home/vzool/.local/app/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/vzool/.local/app/go/src/testing/testing.go:1212 +0x218
panic({0x797980, 0xc00022c0f0})
	/home/vzool/.local/app/go/src/runtime/panic.go:1038 +0x215
entgo.io/ent/examples/fs/ent.(*FileSelect).StringsX(...)
	/home/vzool/Workspace/ent/examples/fs/ent/file_query.go:868
entgo.io/ent/examples/fs.TestExample_RecursiveTraversal(0x0)
	/home/vzool/Workspace/ent/examples/fs/example_test.go:101 +0xd12
testing.tRunner(0xc0000b2ea0, 0x80d0e8)
	/home/vzool/.local/app/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/home/vzool/.local/app/go/src/testing/testing.go:1306 +0x35a
FAIL	entgo.io/ent/examples/fs	0.040s
FAIL
```







## Current Behavior for `PostgreSQL` 😯



```golang
// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"testing"

	"entgo.io/ent/dialect"
	"entgo.io/ent/examples/fs/ent"
	"entgo.io/ent/examples/fs/ent/file"

	entSQL "entgo.io/ent/dialect/sql"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func TestExample_RecursiveTraversal(t *testing.T) {

	db, err := sql.Open("pgx", "postgresql://postgres:postgres@127.0.0.1/postgres")
	if err != nil {
		log.Fatalf("failed opening connection to PostgreSQL: %v", err)
	}
	driver := entSQL.OpenDB(dialect.Postgres, db)
	client := ent.NewClient(ent.Driver(driver))

	defer client.Close()
	ctx := context.Background()
	// Run the auto migration tool.
	if err := client.Schema.Create(ctx); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}

	// Add multiple files in the following tree structure:
	//
	//	a/
	//	├─ b/
	//	│  ├─ ba
	//	│  ├─ bb
	//	│  └─ bc (deleted)
	//	├─ c/ (deleted)
	//	│  ├─ ca
	//	│  └─ cb
	//	└─ d (deleted)
	//
	a := client.File.Create().SetName("a").SaveX(ctx)
	b := client.File.Create().SetName("b").SetParent(a).SaveX(ctx)
	client.File.Create().SetName("ba").SetParent(b).SaveX(ctx)
	client.File.Create().SetName("bb").SetParent(b).SaveX(ctx)
	client.File.Create().SetName("bc").SetParent(b).SetDeleted(true).SaveX(ctx)
	c := client.File.Create().SetName("c").SetParent(a).SetDeleted(true).SaveX(ctx)
	client.File.Create().SetName("ca").SetParent(c).SaveX(ctx)
	client.File.Create().SetName("cb").SetParent(c).SaveX(ctx)
	client.File.Create().SetName("d").SetParent(a).SetDeleted(true).SaveX(ctx)

	// Query undeleted files:
	//
	//	a/
	//	└─ b/
	//	   ├─ ba
	//	   └─ bb
	//
	names := client.Debug().File.Query(). /*[UPDATED-LINE]*/
						Where(func(s *entSQL.Selector) {
			t1, t2 := entSQL.Table(file.Table), entSQL.Table(file.Table)
			with := entSQL.WithRecursive("undeleted", file.FieldID, file.FieldParentID)
			with.As(
				// The initial `SELECT` statement executed once at the start,
				// and produces the initial row or rows for the recursion.
				entSQL.Select(t1.Columns(file.FieldID, file.FieldParentID)...).
					From(t1).
					Where(
						entSQL.And(
							entSQL.IsNull(t1.C(file.FieldParentID)),
							entSQL.EQ(t1.C(file.FieldDeleted), false),
						),
					).
					OrderBy(entSQL.Asc(file.FieldID)).Limit(1). /*[UPDATED-LINE]*/
					// Merge the `SELECT` statement above with the following:
					UnionAll(
						// A `SELECT` statement that produces additional rows and recurses by referring
						// to the CTE name (e.g. "undeleted"), and ends when there are no more new rows.
						entSQL.Select(t2.Columns(file.FieldID, file.FieldParentID)...).
							From(t2).
							Join(with).
							On(t2.C(file.FieldParentID), with.C(file.FieldID)).
							Where(
								entSQL.EQ(t1.C(file.FieldDeleted), false),
							).
							OrderBy(entSQL.Asc(file.FieldDeleted)).Limit(2), /*[UPDATED-LINE]*/
					),
			)
			// Join the root `SELECT` query with the CTE result (`WITH` clause).
			s.Prefix(with).Join(with).On(s.C(file.FieldID), with.C(file.FieldID))
		}).
		Select(file.FieldName).
		StringsX(ctx)
	fmt.Printf("%q\n", names)

	// Output:
	// ["a" "b" "ba" "bb"]
}

```

## Expected Behavior 🤔
Explained above.


## Steps to Reproduce 🕹






Steps:

1. Run `PostgreSQL` docker instance 
```shell
docker run -p 5432:5432 \
        --name postgres \
        -e POSTGRES_PASSWORD=postgres \
        -d postgres:14-alpine
```
2. Update this file [ent/examples/fs/example_test.go](https://github.com/ent/ent/blob/master/examples/fs/example_test.go) like example above.
3. Run the unit test.
4. I hope you meet the bug.

## Your Environment 🌎



| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | 0.9.1   |
| Database    | PostgreSQL   |
| Driver      | [github.com/jackc/pgx/v4/stdlib](https://github.com/jackc/pgx)        |
