### ISSUE TITLE
Invalid memory address or nil pointer dereference with Edge schemas when trying the User Likes Example

### ISSUE THREAD

**Issue by yashdiniz** [ent/ent#2928]
I was trying the User Likes Example(https://entgo.io/docs/schema-edges/#user-likes-example) of the ent docs, and got a SIGSEGV when I ran the command `ent describe ./ent/schema`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When running `ent describe ./ent/schema/`, receive a SIGSEGV.
``` bash
$ ent describe ./ent/schema/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x910f1a]

goroutine 1 [running]:
entgo.io/ent/cmd/internal/printer.Config.node({{0xb8a200?, 0xc00012e008?}}, 0xc000250000)
        /home/yash/go/pkg/mod/entgo.io/ent@v0.11.2/cmd/internal/printer/printer.go:53 +0x41a
entgo.io/ent/cmd/internal/printer.Config.Print(...)
        /home/yash/go/pkg/mod/entgo.io/ent@v0.11.2/cmd/internal/printer/printer.go:27
entgo.io/ent/cmd/internal/printer.Fprint(...)
        /home/yash/go/pkg/mod/entgo.io/ent@v0.11.2/cmd/internal/printer/printer.go:33
entgo.io/ent/cmd/internal/base.DescribeCmd.func1(0xc0004a0f00?, {0xc000414ab0, 0x1, 0x1?})
        /home/yash/go/pkg/mod/entgo.io/ent@v0.11.2/cmd/internal/base/base.go:122 +0xc5
github.com/spf13/cobra.(*Command).execute(0xc0004a0f00, {0xc000414a90, 0x1, 0x1})
        /home/yash/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004a0a00)
        /home/yash/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/yash/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/yash/go/pkg/mod/entgo.io/ent@v0.11.2/cmd/ent/ent.go:23 +0xb0
```

## Expected Behavior 🤔
No panic should be thrown, and the schema should be printed.

## Steps to Reproduce 🕹
The example schema pasted below is the same one in the docs for edge schema in the User Likes Example(https://entgo.io/docs/schema-edges/#user-likes-example).
``` go
// ...

// User holds the schema definition for the User entity.
type User struct {
    ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.String("name").
            Default("Unknown"),
    }
}

// Edges of the User.
func (User) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("liked_tweets", Tweet.Type).
            Through("likes", Like.Type),
    }
}

// Tweet holds the schema definition for the Tweet entity.
type Tweet struct {
    ent.Schema
}

// Fields of the Tweet.
func (Tweet) Fields() []ent.Field {
    return []ent.Field{
        field.Text("text"),
    }
}

// Edges of the Tweet.
func (Tweet) Edges() []ent.Edge {
    return []ent.Edge{
        edge.From("liked_users", User.Type).
            Ref("liked_tweets").
            Through("likes", Like.Type),
    }
}

// Like holds the edge schema definition for the Like edge.
type Like struct {
    ent.Schema
}

func (Like) Annotations() []schema.Annotation {
    return []schema.Annotation{
        field.ID("user_id", "tweet_id"),
    }
}

// Fields of the Like.
func (Like) Fields() []ent.Field {
    return []ent.Field{
        field.Time("liked_at").
            Default(time.Now),
        field.Int("user_id"),
        field.Int("tweet_id"),
    }
}

// Edges of the Like.
func (Like) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("user", User.Type).
            Unique().
            Required().
            Field("user_id"),
        edge.To("tweet", Tweet.Type).
            Unique().
            Required().
            Field("tweet_id"),
    }
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.1  |
| Ent         | 0.11.2   |
| Database    | SQLite   |
| Driver      | https://github.com/mattn/go-sqlite3       |

**Comment by a8m** [comment]
Thanks for reporting this @yashdiniz 🙏 

Issue was fixed with #2931
