### ISSUE TITLE
contrib/entgql: panic in edge query outside of graphql context

### ISSUE THREAD

**Issue by asonawalla** [ent/ent#2983]
We're seeing a panic when trying upgrade ent from v0.3.0 -> v0.3.2 and ent/contrib from v0.11.2 -> v0.11.3 when trying to query an edge via the edge name's method.  The panic is being caused by [this line](https://github.com/ent/contrib/blob/master/entgql/template/edge.tmpl#L23) when invoked outside of a graphql server context; `graph.GetFieldContext(ctx)` can return nil, which of course results in a panic when trying to access `.Field.Alias`.

Fingers crossed this is a simple fix, and I'd be happy to contribute if pointed in the right direction.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When a non-unique, non-relay-connection edge exists on a model, calling the method of that edge name will panic when not invoked within a graphql server context.

## Expected Behavior 🤔

Callers should be able to invoke named edge methods whether done so in a graphql server context or otherwise (e.g. in our case, we're using async workers) without panic.

## Steps to Reproduce 🕹

In the entgql [todo example](https://github.com/ent/contrib/tree/master/entgql/internal/todo), remove the relay connection annotation on the [forward](https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/schema/user.go#L45) and [backward](https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/schema/group.go#L44) edge, run codegen `go generate .`, and write a test that calls the `Group()` method on a user.  See my repro here:

```
func TestUserGroupsMethod(t *testing.T) {
	var (
		ec = enttest.Open(t, dialect.SQLite,
			fmt.Sprintf("file:%s-%d?mode=memory&cache=shared&_fk=1",
				t.Name(), time.Now().UnixNano(),
			),
			enttest.WithMigrateOptions(migrate.WithGlobalUniqueID(true)),
		)
		ctx = context.Background()
	)
	defer ec.Close()

	u, err := ec.User.Create().Save(ctx)
	require.NoError(t, err)

	assert.NotPanics(t, func() {
		_, _ = u.Groups(ctx) // throws the panic below
	})
}
```

```
  Error:          func (assert.PanicTestFunc)(0x105452620) should not panic
                          Panic value:    runtime error: invalid memory address or nil pointer dereference
                          Panic stack:    goroutine 15 [running]:
                  runtime/debug.Stack()
                          /opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:24 +0x64
                  github.com/stretchr/testify/assert.didPanic.func1()
                          /Users/azim/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1050 +0x80
                  panic({0x1058ca940, 0x105fcc840})
                          /opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:884 +0x204
                  entgo.io/contrib/entgql/internal/todo/ent.(*User).Groups(0x140000ac1a0, {0x1059d5b70, 0x14000036088})
                          /Users/azim/code/ent-contrib/entgql/internal/todo/ent/gql_edge.go:108 +0x58
                  entgo.io/contrib/entgql/internal/todo.TestUserGroupsMethod.func1()
                          /Users/azim/code/ent-contrib/entgql/internal/todo/user_test.go:48 +0x28
                  github.com/stretchr/testify/assert.didPanic(0x140000dad00?)
                          /Users/azim/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1055 +0x7c
                  github.com/stretchr/testify/assert.NotPanics({0x1059cff60, 0x140000dad00}, 0x1400058f0a0, {0x0, 0x0, 0x0})
                          /Users/azim/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1126 +0x64
                  entgo.io/contrib/entgql/internal/todo.TestUserGroupsMethod(0x140000dad00)
                          /Users/azim/code/ent-contrib/entgql/internal/todo/user_test.go:47 +0x288
                  testing.tRunner(0x140000dad00, 0x1059c9698)
                          /opt/homebrew/Cellar/go/1.19.1/libexec/src/testing/testing.go:1446 +0x10c
                  created by testing.(*T).Run
                          /opt/homebrew/Cellar/go/1.19.1/libexec/src/testing/testing.go:1493 +0x300
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.1 darwin/arm64  |
| Ent         | v0.3.2  |
| Database    | sqlite3   |
| Driver      | github.com/mattn/go-sqlite3       |

**Comment by a8m** [comment]
Hey @asonawalla 👋🏻
@giautm and I discussed this a few days ago in https://github.com/ent/ent/issues/2946. Can you please elaborate on your use case? Is it just for testing or you have other usage?

If it’s for testing, please see this comment: https://github.com/ent/ent/issues/2946#issuecomment-1255495131

**Comment by asonawalla** [comment]
Hey @a8m, thanks for the quick response!

The test was just to demonstrate the bug, we have some library code that's shared by a graphql server and a pool of background workers that reads the same entities. This code sometimes passes ent structs around by reference and since it's library code, we prefer to use these methods in particular because they can lazy load edges if necessary.

The working assumption is that enabling graphql support doesn't necessarily mean we can't use ent directly outside of the context of graphql. Let me know if I've misunderstood.

**Comment by a8m** [comment]
Thanks for explaining, but I have additional questions if you don't mind to ensure we take the right decision 🙏 

> This code sometimes passes ent structs around by reference and since it's library code, we prefer to use these methods in particular because they can lazy load edges if necessary.

Can you elaborate on how the edges are preloaded in case it's not a GraphQL query context? Is it with `With<E>` or the nodes/entities are already loaded by GraphQL and passed to the workers?

**Comment by a8m** [comment]
@giautm, please see: https://github.com/ent/contrib/pull/385

I think we can accept such calls for a BC reason, but fallback to the previous flow (regular eager-loading).

**Comment by a8m** [comment]
Hey @asonawalla, the issue was resolved with v0.3.3.

Can you please pull this version and verify that it works for you? Thanks

**Comment by asonawalla** [comment]
Hey @a8m, we're running v0.3.3 in our prod environment now without issues.  Appreciate the help, feel free to close this issue out.

@giautm I see what you mean re: preloading only in queries, but there are other examples even within our workers that leverage the same library code, where some callers will eager-load edges and others won't.

I think it's advantageous to be able to write application code that doesn't necessarily care about eager- vs lazy-loading but can take advantage of eager-loading when available.  In fact, one of my favorite parts of using ent is not having to think about DB access patterns (most of the time) - we can just focus on writing application code!  If you think this is an anti-pattern or wrong for some other reason, I'd be curious to know why.

Thanks again for the help!
