### ISSUE TITLE
Internal system error on GraphQL query

### ISSUE THREAD

**Issue by diazoxide** [ent/ent#3256]
After upgrading to last `master` commit I'm getting internal system error when trying to run simple query with edges

- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Server output is
```
runtime error: invalid memory address or nil pointer dereference

goroutine 284 [running]:
runtime/debug.Stack()
        /Users/diazoxide/sdk/go1.19/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /Users/diazoxide/sdk/go1.19/src/runtime/debug/stack.go:16 +0x1c
github.com/99designs/gqlgen/graphql.DefaultRecover({0x5000?, 0x1400080f400?}, {0x101df19e0?, 0x1027217f0?})
        /Users/diazoxide/go/pkg/mod/github.com/99designs/gqlgen@v0.17.5-0.20220428154617-9250f9ac1f90/graphql/recovery.go:17 +0x78
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x1400069a140?, {0x101f47d60, 0x1400092aed0}, {0x101df19e0?, 0x1027217f0?})
        /Users/diazoxide/go/pkg/mod/github.com/99designs/gqlgen@v0.17.5-0.20220428154617-9250f9ac1f90/graphql/context_operation.go:114 +0x44
github.com/diazoxide/ent-refine/examples/ent-project.(*executionContext)._Query_warehouses.func1()
        /Users/diazoxide/GolandProjects/ent-refine/examples/ent-project/gql-generated.go:13844 +0x68
```

## Expected Behavior 🤔

This is bug and should be fixed.

## Steps to Reproduce 🕹

Steps:

```graphql
query ($where: WarehouseWhereInput!, $first: Int) {
  warehouses(where: $where, first: $first) {
    edges {
      node {
        id
        name
        lastUpdate
        originalData
        enabled
        filters
        products {
          pageInfo{
            startCursor
          }
          edges {
            node {
              id
              name
            }
          }
        }
        vendor {
          id
          name
        }
      }
    }
  }
}
```

Variables
```json
{
  "where": {
    "id": "0769603b-0140-41a0-bc7b-d8d3067dd300"
  },
  "first": 1
}
```

Getting response
```json
{
  "errors": [
    {
      "message": "internal system error",
      "path": [
        "warehouses"
      ]
    }
  ],
  "data": null
}
```

But when I'm removing `product` field from query everything is working 
```graphql
        products {
          pageInfo{
            startCursor
          }
          edges {
            node {
              id
              name
            }
          }
        }
```
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         |  master   |
| Database    | SQLite   |

**Comment by a8m** [comment]
Hey @diazoxide, and thanks for reporting this 🙏 
What versions do you use for `entgo.io/contrib` and `gqlgen`?

**Comment by diazoxide** [comment]
@a8m all packages are @master last references.
