### ISSUE TITLE
dialect/sql: Schema WriteDriver noRows does not implement Columns

### ISSUE THREAD

**Issue by process0** [ent/ent#3294]
When using a `schema.WriterDriver` with queries that return columns, the driver will nil pointer dereference.

This is due to the `noRows` type not implementing the `Columns` method. Adding the following seems to fix:

```go
func (noRows) Columns() ([]string, error) { return []string{}, nil }
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
```
goroutine 1 [running]:
entgo.io/ent/dialect/sql/schema.(*noRows).Columns(0x7f070ef96d28?)
        <autogenerated>:1 +0x24
entgo.io/ent/dialect/sql.ScanOne({0x19dbd90, 0xc000335820}, {0x1519820?, 0xc00063c4f8})
        /go/pkg/mod/entgo.io/ent@v0.11.7/dialect/sql/scan.go:19 +0x3a
entgo.io/ent/dialect/sql/sqlgraph.(*creator).insertLastID(0xc000483b20, {0x19d84f0, 0xc00003a128}, 0xc0003a1a48)
        /go/pkg/mod/entgo.io/ent@v0.11.7/dialect/sql/sqlgraph/graph.go:1529 +0x305
entgo.io/ent/dialect/sql/sqlgraph.(*creator).insert(0xc000483b20, {0x19d84f0, 0xc00003a128}, 0xc0003a1a48)
        /go/pkg/mod/entgo.io/ent@v0.11.7/dialect/sql/sqlgraph/graph.go:1074 +0x449
entgo.io/ent/dialect/sql/sqlgraph.(*creator).node.func1(0xc000483b20, 0x19d84f0?, {0x19d84f0, 0xc00003a128}, 0xc00062fb90?)
        /go/pkg/mod/entgo.io/ent@v0.11.7/dialect/sql/sqlgraph/graph.go:1027 +0x68
entgo.io/ent/dialect/sql/sqlgraph.(*creator).node(0xc000483b20, {0x19d84f0, 0xc00003a128}, {0x19da860, 0xc00062fb90})
        /go/pkg/mod/entgo.io/ent@v0.11.7/dialect/sql/sqlgraph/graph.go:1034 +0x2a5
entgo.io/ent/dialect/sql/sqlgraph.CreateNode({0x19d84f0, 0xc00003a128}, {0x19da860?, 0xc00062fb90?}, 0xc0003400e0)
        /go/pkg/mod/entgo.io/ent@v0.11.7/dialect/sql/sqlgraph/graph.go:398 +0x133
```
## Expected Behavior 🤔

Not panic

## Steps to Reproduce 🕹
```go
    var b bytes.Buffer
    driver := schema.NewWriteDriver("sqlite3", io.Writer(&b))
    client := ent.NewClient(ent.Driver(driver))

    client.Cats.Create().SetID("predeterminedcat").OnConflict().Ignore().Exec(ctx)
```
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.11.7   |
| Database    | Sqlite3   |

**Comment by masseelch** [comment]
Hello @process0. This was fixed in #3369. If you still experience errors, please don't hesitate to open a new issue.
