### ISSUE TITLE
multi channel execute migrate cause fatal error

### ISSUE THREAD

**Issue by alicfeng** [ent/ent#3486]
my project has many sqlite data,so nedd to migrate at together when playform  upgrate. my code is 

```golang
	migrateChannelSize := m.conf.MigrateChannelSize
	if migrateChannelSize <= 0 {
		migrateChannelSize = 50
	}
	log.Infof("sqlite migrate channel size %d", migrateChannelSize)
	var wg sync.WaitGroup
	ch := make(chan struct{}, migrateChannelSize)
	for index, tk := range tasks {
		log.Infof("sqlite migrate processing %d/%d", index+1, len(tasks))

		ch <- struct{}{}
		wg.Add(1)
		go func(task *ent.Task) {
			defer wg.Done()
			m.migrate(tk)
			<-ch
		}(tk)
	}

	wg.Wait()

	log.Infof("sqlite migration had finished")
```

error log is 
```
2023/04/17 09:14:58 driver.Query: query=PRAGMA foreign_keys args=[]
2023/04/17 09:14:58 driver.Exec: query=PRAGMA foreign_keys = off args=[]
2023/04/17 09:14:58 Tx(978e7942-aa34-4b11-99e9-dfce4e8083a6).Query: query=SELECT name FROM pragma_collation_list() args=[]
2023/04/17 09:14:58 driver.Query: query=PRAGMA foreign_keys args=[]
2023/04/17 09:14:58 driver.Query: query=PRAGMA foreign_keys args=[]
2023/04/17 09:14:58 driver.Exec: query=PRAGMA foreign_keys = off args=[]
fatal error: concurrent map writes

goroutine 125 [running]:
runtime.throw({0x12a57ca?, 0xc000a80c00?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0009e5ca8 sp=0xc0009e5c78 pc=0x452c11
runtime.mapassign_faststr(0x110df00?, 0xc0003acb10?, {0x129301a, 0x2})
	/usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc0009e5d10 sp=0xc0009e5ca8 pc=0x431b9c
entgo.io/ent/dialect/sql/schema.(*Atlas).setupTables(0xc000490ce0?, {0x1e03560, 0xf, 0xc000a84380?})
	/root/go/pkg/mod/entgo.io/ent@v0.11.9/dialect/sql/schema/atlas.go:1028 +0x1a5 fp=0xc0009e5e00 sp=0xc0009e5d10 pc=0xa1e045
entgo.io/ent/dialect/sql/schema.(*Atlas).Create(0xc000a84380, {0x1469990, 0xc00019c000}, {0x1e03560, 0xf, 0xf})
	/root/go/pkg/mod/entgo.io/ent@v0.11.9/dialect/sql/schema/atlas.go:105 +0x45 fp=0xc0009e5e50 sp=0xc0009e5e00 pc=0xa15bc5
```

**Comment by a8m** [comment]
Hey, @alicfeng 👋 
Can you elaborate on your use case? Why run multiple migrations concurrently?

Also, can you run your code on the latest Ent version, so I'll have an updated stack trace? Thanks

**Comment by alicfeng** [comment]
> Hey, @alicfeng wave Can you elaborate on your use case? Why run multiple migrations concurrently?
> 
> Also, can you run your code on the latest Ent version, so I'll have an updated stack trace? Thanks

This is the case, because the saas platform stores each user's data in an independent sqlite3 database file. There are currently many database files. When upgrading, the table structure needs to be updated. The method without using coroutines will be very slow. ths @a8m
