### ISSUE TITLE
entgo.io/ent/dialect/sql/schema.Table.columns has concurrent writes

### ISSUE THREAD

**Issue by willfaught** [ent/ent#3643]
- [x] The issue is present in the latest release.

As far as I know. I tried to use the latest version, but hit a [bug](https://github.com/ent/ent/issues/3642).

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
$ go test
fatal error: concurrent map writes

goroutine 9 [running]:
entgo.io/ent/dialect/sql/schema.(*Atlas).setupTables(0xc00052e1f0?, {0x1035886a0, 0x35, 0xc00058c000?})
	/Users/Will/Library/Application Support/go/pkg/mod/entgo.io/ent@v0.11.4-0.20221001062602-1029a2d3ba2a/dialect/sql/schema/atlas.go:924 +0x1b4
entgo.io/ent/dialect/sql/schema.(*Atlas).Create(0xc00058c000, {0x102502be8, 0xc0000a6018}, {0x1035886a0, 0x35, 0x35})
	/Users/Will/Library/Application Support/go/pkg/mod/entgo.io/ent@v0.11.4-0.20221001062602-1029a2d3ba2a/dialect/sql/schema/atlas.go:103 +0x45
github.com/account/repo/ent/migrate.Create({0x102502be8, 0xc0000a6018}, 0x1?, {0x1035886a0, 0x35, 0x35}, {0xc0005896d0?, 0x0?, 0x0?})
	/Users/Will/Developer/repo/ent/migrate/migrate.go:54 +0xb6
github.com/account/repo/ent/migrate.(*Schema).Create(...)
	/Users/Will/Developer/repo/ent/migrate/migrate.go:45
github.com/account/repo/database.Client()
	/Users/Will/Developer/repo/database/client.go:45 +0x42d
github.com/account/repo/testutil.NewClient(...)
	/Users/Will/Developer/repo/testutil/util.go:29
github.com/account/repo/testutil.SetupForQueries(0xc0004af6c0?)
	/Users/Will/Developer/repo/testutil/util.go:17 +0x31
github.com/account/repo/graph/banner.TestGetBanners(0xc0004af6c0)
	/Users/Will/Developer/repo/graph/banner/banner_test.go:131 +0x5a
testing.tRunner(0xc0004af6c0, 0x1020c5eb8)
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1629 +0x3ea

goroutine 1 [chan receive]:
testing.tRunner.func1()
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1542 +0x4a5
testing.tRunner(0xc0004aeea0, 0xc00065fc88)
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1582 +0x144
testing.runTests(0xc00046e780?, {0x103586ac0, 0xa, 0xa}, {0x20?, 0x100c00056e9e8?, 0x1035979a0?})
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc00046e780)
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:65 +0x1aa

goroutine 8 [runnable]:
entgo.io/ent/dialect/sql/schema.(*Atlas).symbol(0xc0001ded20?, {0x101ff9269, 0x21?})
	/Users/Will/Library/Application Support/go/pkg/mod/entgo.io/ent@v0.11.4-0.20221001062602-1029a2d3ba2a/dialect/sql/schema/atlas.go:947 +0x131
entgo.io/ent/dialect/sql/schema.(*Atlas).setupTables(0xc0003ddd10?, {0x1035886a0, 0x35, 0xc0001ded20?})
	/Users/Will/Library/Application Support/go/pkg/mod/entgo.io/ent@v0.11.4-0.20221001062602-1029a2d3ba2a/dialect/sql/schema/atlas.go:938 +0x3ad
entgo.io/ent/dialect/sql/schema.(*Atlas).Create(0xc0001ded20, {0x102502be8, 0xc0000a6018}, {0x1035886a0, 0x35, 0x35})
	/Users/Will/Library/Application Support/go/pkg/mod/entgo.io/ent@v0.11.4-0.20221001062602-1029a2d3ba2a/dialect/sql/schema/atlas.go:103 +0x45
github.com/account/repo/ent/migrate.Create({0x102502be8, 0xc0000a6018}, 0x1?, {0x1035886a0, 0x35, 0x35}, {0xc000161880?, 0x0?, 0x0?})
	/Users/Will/Developer/repo/ent/migrate/migrate.go:54 +0xb6
github.com/account/repo/ent/migrate.(*Schema).Create(...)
	/Users/Will/Developer/repo/ent/migrate/migrate.go:45
github.com/account/repo/database.Client()
	/Users/Will/Developer/repo/database/client.go:45 +0x42d
github.com/account/repo/testutil.NewClient(...)
	/Users/Will/Developer/repo/testutil/util.go:29
github.com/account/repo/testutil.SetupForQueries(0xc0004af520?)
	/Users/Will/Developer/repo/testutil/util.go:17 +0x31
github.com/account/repo/graph/banner.TestGetBanner(0xc0004af520)
	/Users/Will/Developer/repo/graph/banner/banner_test.go:50 +0x45
testing.tRunner(0xc0004af520, 0x1020c5ec0)
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/Cellar/go/1.20.5/libexec/src/testing/testing.go:1629 +0x3ea

goroutine 16 [select]:
database/sql.(*DB).connectionOpener(0xc00012b040, {0x102502bb0, 0xc0000c5590})
	/usr/local/Cellar/go/1.20.5/libexec/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/usr/local/Cellar/go/1.20.5/libexec/src/database/sql/sql.go:791 +0x18d

goroutine 50 [select]:
database/sql.(*DB).connectionOpener(0xc0002c0f70, {0x102502bb0, 0xc000108050})
	/usr/local/Cellar/go/1.20.5/libexec/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/usr/local/Cellar/go/1.20.5/libexec/src/database/sql/sql.go:791 +0x18d
FAIL	github.com/account/repo	0.512s
FAIL
```

## Expected Behavior 🤔

No panic.

## Steps to Reproduce 🕹

Have two tests that run in parallel that each do a migration.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go version go1.20.5 darwin/amd64  |
| Ent         | v0.11.4-0.20221001062602-1029a2d3ba2a     |
| Database    | PostgreSQL   |
| Driver      | github.com/lib/pq  |

**Comment by a8m** [comment]
Hey @willfaught 👋 

In order to run tests in parallel use the generated `enttest` package (this was added to it here: https://github.com/ent/ent/pull/2665). More info can be found here: https://entgo.io/docs/testing

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by willfaught** [comment]
Thanks for the response.

Couldn't a mutex just be added to avoid this problem?

**Comment by a8m** [comment]
I wouldn't mix testing code with production code, as users only run migrations once on real environments. 

Also, note that copying tables is faster than using a lock to sync schema migrations.

In any case, using enttest should simply solve the issue, so I suggest just to use this for creating clients in testing code.
