### ISSUE TITLE
Ent generate panics with Go 1.22

### ISSUE THREAD

**Issue by marwan-at-work** [ent/ent#3864]
Hi there 👋🏼👋🏼 

Thought I'd give y'all a heads up, Go1.22rc1 is out and it panics with ent. 

To reproduce: go through the simple getting started guide [here](https://entgo.io/docs/getting-started) and you should end up with the following: 

```
$ go generate ./ent
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101421ee0]

goroutine 7 [running]:
go/types.(*Checker).handleBailout(0x140001d8600, 0x140004c5b98)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x101712f00?, 0x101b14bf0?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x1017ab050, 0x101b1b3a0})
        /usr/local/go/src/go/types/sizes.go:228 +0x320
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x1017ab050?, 0x101b1b3a0?})
        /usr/local/go/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x1017ae080, 0x101b3c1c0}, 0x140001d8600, 0x101b1b3a0, 0x140004c4838)
        /usr/local/go/src/go/types/const.go:106 +0x2b0
go/types.(*Checker).representation(0x140001d8600, 0x14000472400, 0x101b1b3a0)
        /usr/local/go/src/go/types/const.go:256 +0x68
go/types.(*Checker).representable(0x140001d8600, 0x14000472400, 0x101b1b3a0)
        /usr/local/go/src/go/types/const.go:239 +0x28
go/types.(*Checker).shift(0x140001d8600, 0x140004723c0, 0x14000472400, {0x1017ad120, 0x14000156cf0}, 0x14)
        /usr/local/go/src/go/types/expr.go:650 +0x1d8
go/types.(*Checker).binary(0x140001d8600, 0x140004723c0, {0x1017ad120, 0x14000156cf0}, {0x1017ad690, 0x140002feca0}, {0x1017ace80, 0x140002fecc0}, 0x14, 0x243e05)
        /usr/local/go/src/go/types/expr.go:796 +0x100
go/types.(*Checker).exprInternal(0x140001d8600, 0x0, 0x140004723c0, {0x1017ad120, 0x14000156cf0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140001d8600, 0x0, 0x140004723c0, {0x1017ad120?, 0x14000156cf0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140001d8600, 0x1400023e5b0?, 0x140004723c0, {0x1017ad120?, 0x14000156cf0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).constDecl(0x140001d8600, 0x1400011f740, {0x1017ace80, 0x140002fec80}, {0x1017ad120, 0x14000156cf0}, 0x0)
        /usr/local/go/src/go/types/decl.go:488 +0x284
go/types.(*Checker).objDecl(0x140001d8600, {0x1017b31c0, 0x1400011f740}, 0x0)
        /usr/local/go/src/go/types/decl.go:191 +0x84c
go/types.(*Checker).packageObjects(0x140001d8600)
        /usr/local/go/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x140001d8600, {0x140002925d0, 0x2, 0x2})
        /usr/local/go/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x140001ca8c0, 0x140000b29c0)
        /Users/marwan/go/pkg/mod/golang.org/x/tools@v0.8.1-0.20230428195545-5283a0178901/go/packages/packages.go:1052 +0x870
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/marwan/go/pkg/mod/golang.org/x/tools@v0.8.1-0.20230428195545-5283a0178901/go/packages/packages.go:851 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/marwan/go/pkg/mod/golang.org/x/tools@v0.8.1-0.20230428195545-5283a0178901/go/packages/packages.go:839 +0x50
golang.org/x/tools/go/packages.(*loader).refine.func2(0x0?)
        /Users/marwan/go/pkg/mod/golang.org/x/tools@v0.8.1-0.20230428195545-5283a0178901/go/packages/packages.go:774 +0x30
created by golang.org/x/tools/go/packages.(*loader).refine in goroutine 1
        /Users/marwan/go/pkg/mod/golang.org/x/tools@v0.8.1-0.20230428195545-5283a0178901/go/packages/packages.go:773 +0xaa4
ent/generate.go:3: running "ent": exit status 2
```

Thanks for keeping this project up to date! 🎉

**Comment by database64128** [comment]
Just a heads-up: Go 1.22.0 is out and running `go generate ./ent` still panics like this.

**Comment by a8m** [comment]
hey! I updated x/tools to latest and it should solve the issue. Please, reopen if you still have problems with it.

**Comment by database64128** [comment]
@a8m Any plans for making a new release? Having to add `@master` to all of my projects using ent is not something I enjoy doing. Thanks.

**Comment by gonnafaraway** [comment]
Hi there!
I'm sure your project is lower then 1.22 go version
Bump version of project to 1.22 and error will be solved!

And again:
- go must be 1.22 version
- ent must be the latest version
- go in go.mod must be 1.22 version
Good luck!

**Comment by gonnafaraway** [comment]
and if you check, ent latest version now is 1.21.*
1.22+ not supported yet.
